remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Site Settings
locale                   : "en"
title                    : "Metalamin Blog"
title_separator          : "-"
name                     : &name "Metalamin Labs"
description              : &description "Personal Blog - Metalamin"
url                      : "https://metalamin.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "metalamin/metalamin.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
search                   : true

# Social Sharing
twitter:
  username: &twitter "metalamin"
  
# Site Author  
author:
  name   : "Amine Taouirsa"
  avatar : "/assets/images/Bio.jpg"
  bio: "How about ... 'xchg eax, eax'!!"
  location: "Madrid, Spain"
  email  : # optional
  uri    : "http://metalamin.github.io"
  home   :
  telegram : "metalamin"
  github : "metalamin"
  twitter: *twitter

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: false
      

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Madrid # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-76198646-2"
google_site_verification: "OdWSISFYeXwWMKyR4XGqSQEBjh71eR9sFpoqqRCcV58"

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
