atheme: jekyll-theme-slate
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Site Settings
locale                   : "es"
title                    : "Metalamin Site"
title_separator          : "-"
name                     : "Metalamin"
description              : "Ze amazing website."
url                      : "https://metalamin.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "metalamin/metalamin.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
search                   : true


twitter:
  username: "metalamin"
  
  
author:
  name   : "Your Name"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  email  : # optional
  uri    : "https://metalamin.github.io"
  home   :

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
